//D
package ua.itea.javabasic.practice.lesson03.flip_matrix;
import java.io.*;
public  class Main {
    public static void main(String[]args) throws Exception {
        BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
        System.out.println("Please enter the sixteen-element array 4x4 (byte type (from 10 to 99)): ");
        byte[][] b = new byte [4][4];
        String sb00 = reader.readLine();
        String sb01 = reader.readLine();
        String sb02 = reader.readLine();
        String sb03 = reader.readLine();
        String sb10 = reader.readLine();
        String sb11 = reader.readLine();
        String sb12 = reader.readLine();
        String sb13 = reader.readLine();
        String sb20 = reader.readLine();
        String sb21 = reader.readLine();
        String sb22 = reader.readLine();
        String sb23 = reader.readLine();
        String sb30 = reader.readLine();
        String sb31 = reader.readLine();
        String sb32 = reader.readLine();
        String sb33 = reader.readLine();
        b[0][0] = Byte.parseByte(sb00);
        b[0][1] = Byte.parseByte(sb01);
        b[0][2] = Byte.parseByte(sb02);
        b[0][3] = Byte.parseByte(sb03);
        b[1][0] = Byte.parseByte(sb10);
        b[1][1] = Byte.parseByte(sb11);
        b[1][2] = Byte.parseByte(sb12);
        b[1][3] = Byte.parseByte(sb13);
        b[2][0] = Byte.parseByte(sb20);
        b[2][1] = Byte.parseByte(sb21);
        b[2][2] = Byte.parseByte(sb22);
        b[2][3] = Byte.parseByte(sb23);
        b[3][0] = Byte.parseByte(sb30);
        b[3][1] = Byte.parseByte(sb31);
        b[3][2] = Byte.parseByte(sb32);
        b[3][3] = Byte.parseByte(sb33);

        System.out.println();
        System.out.println("You entered array:");
        System.out.println(b[0][0]+"  "+b[0][1]+"  "+b[0][2]+"  "+b[0][3]);
        System.out.println(b[1][0]+"  "+b[1][1]+"  "+b[1][2]+"  "+b[1][3]);
        System.out.println(b[2][0]+"  "+b[2][1]+"  "+b[2][2]+"  "+b[2][3]);
        System.out.println(b[3][0]+"  "+b[3][1]+"  "+b[3][2]+"  "+b[3][3]);

        //flip horizontal;
        byte temp;
        temp = b[0][0];
        b[0][0] = b[3][0];
        b[3][0] = temp;
        temp = b[0][1];
        b[0][1] = b[3][1];
        b[3][1] = temp;
        temp = b[0][2];
        b[0][2] = b[3][2];
        b[3][2] = temp;
        temp = b[0][3];
        b[0][3] = b[3][3];
        b[3][3] = temp;
        temp = b[1][0];
        b[1][0] = b[2][0];
        b[2][0] = temp;
        temp = b[1][1];
        b[1][1] = b[2][1];
        b[2][1] = temp;
        temp = b[1][2];
        b[1][2] = b[2][2];
        b[2][2] = temp;
        temp = b[1][3];
        b[1][3] = b[2][3];
        b[2][3] = temp;

        //flip vertically;
        temp = b[0][0];
        b[0][0] = b[0][3];
        b[0][3] = temp;
        temp = b[0][1];
        b[0][1] = b[0][2];
        b[0][2] = temp;
        temp = b[1][0];
        b[1][0] = b[1][3];
        b[1][3] = temp;
        temp = b[1][1];
        b[1][1] = b[1][2];
        b[1][2] = temp;
        temp = b[2][0];
        b[2][0] = b[2][3];
        b[2][3] = temp;
        temp = b[2][1];
        b[2][1] = b[2][2];
        b[2][2] = temp;
        temp = b[3][0];
        b[3][0] = b[3][3];
        b[3][3] = temp;
        temp = b[3][1];
        b[3][1] = b[3][2];
        b[3][2] = temp;

        System.out.println();
        System.out.println("Result array is:");
        System.out.println(b[0][0]+"  "+b[0][1]+"  "+b[0][2]+"  "+b[0][3]);
        System.out.println(b[1][0]+"  "+b[1][1]+"  "+b[1][2]+"  "+b[1][3]);
        System.out.println(b[2][0]+"  "+b[2][1]+"  "+b[2][2]+"  "+b[2][3]);
        System.out.println(b[3][0]+"  "+b[3][1]+"  "+b[3][2]+"  "+b[3][3]);
    }
}
